// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/03/2025, 11:42:26
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/plugins/**/*.{js,ts,mjs}","/home/project/composables/**/*.{js,ts,mjs}","/home/project/utils/**/*.{js,ts,mjs}","/home/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":{"50":"#E6FFF5","100":"#CCFFEB","200":"#99FFD6","300":"#66FFC2","400":"#33FFAD","500":"#01DB87","600":"#00B26F","700":"#008A56","800":"#00613D","900":"#003924","DEFAULT":"#01DB87"}},"fontFamily":{"sans":["Lato","sans-serif"]}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;